# Generated by Django 3.1 on 2020-10-31 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20201031_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.location'),
        ),
    ]
