# Generated by Django 3.1 on 2020-10-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20201031_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
