# Generated by Django 3.1 on 2020-10-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20201031_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='occupied',
            field=models.IntegerField(blank=True),
        ),
    ]
