# Generated by Django 3.1 on 2020-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_auto_20201031_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='occupied',
            field=models.IntegerField(null=True),
        ),
    ]
