# Generated by Django 3.1 on 2020-11-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_hospital_hid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='spec',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
