# Generated by Django 3.1 on 2020-11-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_auto_20201105_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='book1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='book2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='book3',
            field=models.IntegerField(null=True),
        ),
    ]
