# Generated by Django 3.1 on 2020-11-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_auto_20201105_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='book1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slot',
            name='book2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slot',
            name='book3',
            field=models.IntegerField(default=0),
        ),
    ]
