# Generated by Django 3.1 on 2020-11-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0016_auto_20201105_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timings',
            field=models.CharField(default='-', max_length=15),
        ),
    ]
