# Generated by Django 3.1 on 2020-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0017_appointment_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
