# Generated by Django 3.1 on 2020-11-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0018_appointment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
